# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
# --- H2 CONSOLE ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# --- SQL INIT ---
spring.sql.init.data-locations=classpath:sql/manufacturer.sql,\
  classpath:sql/client.sql,\
  classpath:sql/employee.sql,\
  classpath:sql/appliance.sql,\
  classpath:sql/orders.sql
#  classpath:sql/orders.sql, \
# --- LOGGING ---
logging.level.root=INFO
logging.level.com.epam.rd.autocode.assessment.appliances=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG